// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoIySBA_oWMABtJUFIeU53OL0shg3kHGg',
    appId: '1:1081856499302:web:6e713142b0c8e662c717a7',
    messagingSenderId: '1081856499302',
    projectId: 'tp-flutter-7130c',
    authDomain: 'tp-flutter-7130c.firebaseapp.com',
    storageBucket: 'tp-flutter-7130c.firebasestorage.app',
    measurementId: 'G-5SL16HB4Q0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYnH7_3SQ8-Ce4r55ltp5AlgGUbIczGCQ',
    appId: '1:1081856499302:android:f0070f21e954b242c717a7',
    messagingSenderId: '1081856499302',
    projectId: 'tp-flutter-7130c',
    storageBucket: 'tp-flutter-7130c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCITRCKScPJuhOZpui7OEuCTw6XDDVPUzQ',
    appId: '1:1081856499302:ios:b2a0752490f8b59dc717a7',
    messagingSenderId: '1081856499302',
    projectId: 'tp-flutter-7130c',
    storageBucket: 'tp-flutter-7130c.firebasestorage.app',
    iosClientId: '1081856499302-dgkj8vm6pfurij1jnu5rcaklsvifvavd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCITRCKScPJuhOZpui7OEuCTw6XDDVPUzQ',
    appId: '1:1081856499302:ios:b2a0752490f8b59dc717a7',
    messagingSenderId: '1081856499302',
    projectId: 'tp-flutter-7130c',
    storageBucket: 'tp-flutter-7130c.firebasestorage.app',
    iosClientId: '1081856499302-dgkj8vm6pfurij1jnu5rcaklsvifvavd.apps.googleusercontent.com',
    iosBundleId: 'com.example.tpFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoIySBA_oWMABtJUFIeU53OL0shg3kHGg',
    appId: '1:1081856499302:web:e9d70d42d7746e55c717a7',
    messagingSenderId: '1081856499302',
    projectId: 'tp-flutter-7130c',
    authDomain: 'tp-flutter-7130c.firebaseapp.com',
    storageBucket: 'tp-flutter-7130c.firebasestorage.app',
    measurementId: 'G-CKZS35QYDN',
  );
}
